on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  run-unit-tests:
    name: Fake action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - id: list-s3-dirs
        shell: bash
        run: |
          echo ${{ github.ref_name }}
