on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  run-unit-tests:
    name: Fake action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - id: list-s3-dirs
        shell: bash
        run: |
          echo "hello world !" > test.json
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          base: main
          add-paths: |
            test.json
          commit-message: 'Update test.json'
          committer: github-actions <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-releases-presets
          assignees: ${{ github.actor }}
          title: 'Cool test'
          body: |
            Github actions opening PRs over here
            cc @${{ github.actor }}
            cc ${{ github.actor }}
