on:
  release:
    types: [created]

jobs:
  run-unit-tests:
    name: Fake action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - id: list-s3-dirs
        shell: bash
        run: |
          echo "Whatever" > test.json
      - name: Commit files
        run: |
          git config --local user.name "github-actions"
          git add ./test.json
          git diff-index --quiet HEAD || git commit -m "Update test.json"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
